Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Northwind.Models;

namespace Northwind.Controllers
{
    public class CustomerController : Controller
    {
        private INorthwindRepository repository;

        public CustomerController(INorthwindRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(Customer customer)
        {
            if (ModelState.IsValid)
            {
                repository.AddCustomer(customer);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Northwind.Models;

namespace Northwind.Controllers
{
    public class ProductController : Controller
    {
        private INorthwindRepository repository;

        public ProductController(INorthwindRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Category()
        {
            var categories = repository.Categories.OrderBy(c => c.CategoryName);

            return View(categories);
        }

        public IActionResult Index(String id)
        {
            var products = repository.Products;

            if(id!=null)
            {
                products = repository.Products.Where(p => p.CategoryId == id && p.Discontinued == false).OrderBy(p => p.ProductName);
            }
            return View(products);
        }

        public IActionResult CurentDiscounts()
        {
            var discounts = repository.Discounts.Where(d => d.EndTime.Date > DateTime.Now && d.StartTime.Date < DateTime.Now).OrderBy(d => d.EndTime);

            return View(discounts);
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- bootstrap -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
    <link href="/css/bootstrap-custom.min.css" rel="stylesheet" />
    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <!-- client -->
    <link rel="stylesheet" href="/css/client.css" />
    <!--Animate.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" />
</head>
<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home"><i class="far fa-compass"></i> Northwind</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-database"></i> Products
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-action="Category" asp-controller="Product"><i class="fas fa-list-ul"></i> Browse Categories</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-search"></i> Product Search</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-action="CurentDiscounts" asp-controller="Product"><i class="fas fa-tag"></i> Current Discounts</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-users"></i> Customers
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#"><i class="fas fa-user-circle"></i>Account</a>
                        <a class="dropdown-item" asp-action="Register" asp-controller="Customer"><i class="fas fa-clipboard"></i>Register</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-pen-square"></i>Sign-In</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Product Search" aria-label="Search">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>
    </nav>
    <div id="toast" class="toast" style="position: absolute; top: 100px; right: 20%;">
        <div class="toast-header">
            <strong class="mr-auto" id="product">Product Name</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Discount Code: <strong id="code">CODE</strong>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>

    <footer>
        <div class="container footerMain">
            <h2>Northwind Traders</h2>
            <div class="row">
                <div class="col-sm"></div>
                <div class="col-sm" id="footLeft">
                    <h5>Connect With Us</h5>
                    <div class='socialMediaIcons'>
                        <div class='fbIcon'></div>
                        <div class='igIcon'></div>
                        <div class='twIcon'></div>
                        <div class='pnIcon'></div>
                    </div>
                    <p class='footerPhoneNumber'>(414)123-4567</p>
                    <br />
                    <br />
                    <a href="#" class='footerContactLink'>Contact Us</a>
                </div>
                <div className="col-sm" id="footMid">
                    <h5></h5>
                </div>
                <div className="col-sm" id="footRight">

                </div>
                <div class="col-sm"></div>
            </div>
            <div class="footBot">
                Copyright &copy; 2019 Team Red Shoes DevTeam
                <br />
                <a href="samtrextom@gmail.com">samtrextom@gmail.com</a>
            </div>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>